name: Build DECtalk

on:
  - push
  - pull_request

jobs:
  ubuntu:
    name: Ubuntu (latest)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Ubuntu Packages
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get -y install build-essential libpulse-dev libgtk2.0-dev unzip autoconf automake

      - name: Run CMake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Make DECtalk
        working-directory: build
        run: make

      - uses: vimtor/action-zip@v1
        with:
          files: build/bin/
          dest: ubuntu-latest.zip

      - name: Create a `.tar.gz` of the build/bin/ folder.
        run: tar -cvzf ubuntu-latest.tar.gz -C build/bin/ .

      - name: Create artifacts (.zip)
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-latest-zip
          path: ubuntu-latest.zip

      - name: Create artifacts (.tar.gz.zip)
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-latest-tar
          path: ubuntu-latest.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ubuntu-latest.tar.gz

  macosx:
    name: Mac OS X
    runs-on: macos-11

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Mac OS X packages
        run: brew update

      - name: Install dependencies
        run: brew install libtool

      - name: Run CMake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Make DECtalk
        working-directory: build
        run: make

      - uses: vimtor/action-zip@v1
        with:
          files: build/bin/
          dest: macos-universal.zip

      - name: Create a `.tar.gz` of the build/bin/ folder.
        run: tar -cvzf macos-universal.tar.gz -C build/bin/ .

      - name: Create artifacts (.zip)
        uses: actions/upload-artifact@v3
        with:
          name: macos-universal-zip
          path: macos-universal.zip

      - name: Create artifacts (.tar.gz.zip)
        uses: actions/upload-artifact@v3
        with:
          name: macos-universal-tar
          path: macos-universal.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            macos-universal.zip
            macos-universal.tar.gz

  vs2022:
    name: Visual Studio 2022
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run CMake
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Make DECtalk
        shell: cmd
        run: devops\vs2022\dt_buildall.bat

      - uses: vimtor/action-zip@v1
        with:
          files: build/bin/
          dest: windows-amd64.zip

      - name: Create artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-amd64-zip
          path: windows-amd64.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            windows-amd64.zip
