name: Build DECtalk

on:
  push:
    branches: ["linux-compile", "windows-compile"]
  pull_request:
    branches: ["linux-compile", "windows-compile"]

jobs:
  ubuntu:
    name: Ubuntu (latest)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Ubuntu Packages
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get -y install build-essential libpulse-dev libgtk2.0-dev unzip autoconf automake

      - name: Create configure files
        working-directory: src
        run: autoreconf -i

      - name: Configure
        working-directory: src
        run: ./configure

      - name: Make DECtalk
        working-directory: src
        run: make

      - name: Create a `.tar.gz` of the dist/ folder.
        working-directory: src
        run: tar -cvzf dectalk.tar.gz -C dist/ .

      - name: Create artifacts (.zip)
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-latest-zip
          path: dist/

      - name: Create artifacts (.tar.gz.zip)
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-latest-tar
          path: dectalk.tar.gz

  windows:
    name: Windows Server 2019
    runs-on: [self-hosted, windows, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make DECtalk
        shell: cmd
        run: devops\windows\dt_buildall.bat

      - name: Copy files to the "/dist" folder
        shell: cmd
        run: devops\windows\dt_copyfiles.bat

      - name: Create artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-server-2019
          path: dist/
